# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='created',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='username',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='catalogo/funcionario'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='enderco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='M', max_length=100, verbose_name='Sexo'),
        ),
    ]
